//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCBManufacturing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCBManufacturing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        public static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to board.
        /// </summary>
        public static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boards.
        /// </summary>
        public static string Boards {
            get {
                return ResourceManager.GetString("Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boards Quantity.
        /// </summary>
        public static string BoardsQuantity {
            get {
                return ResourceManager.GetString("BoardsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Thickness.
        /// </summary>
        public static string BoardThickness {
            get {
                return ResourceManager.GetString("BoardThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        public static string Components {
            get {
                return ResourceManager.GetString("Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlled Impadance.
        /// </summary>
        public static string ControlledImpadance {
            get {
                return ResourceManager.GetString("ControlledImpadance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooper Weight on Liner Layer.
        /// </summary>
        public static string CooperLinerLayer {
            get {
                return ResourceManager.GetString("CooperLinerLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooper Weight on Outer Layer.
        /// </summary>
        public static string CooperOuterLayer {
            get {
                return ResourceManager.GetString("CooperOuterLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Impact.
        /// </summary>
        public static string CostImpact {
            get {
                return ResourceManager.GetString("CostImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_ControlledImpadanceItem_None {
            get {
                return ResourceManager.GetString("Enum_ControlledImpadanceItem_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Notes.
        /// </summary>
        public static string Enum_ControlledImpadanceItem_SeeNotes {
            get {
                return ResourceManager.GetString("Enum_ControlledImpadanceItem_SeeNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.3oz.
        /// </summary>
        public static string Enum_CooperWeightItem_High {
            get {
                return ResourceManager.GetString("Enum_CooperWeightItem_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0oz.
        /// </summary>
        public static string Enum_CooperWeightItem_Low {
            get {
                return ResourceManager.GetString("Enum_CooperWeightItem_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.7oz.
        /// </summary>
        public static string Enum_CooperWeightItem_Medium {
            get {
                return ResourceManager.GetString("Enum_CooperWeightItem_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string Enum_FluxTypeItem_Clean {
            get {
                return ResourceManager.GetString("Enum_FluxTypeItem_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Clean.
        /// </summary>
        public static string Enum_FluxTypeItem_NoClean {
            get {
                return ResourceManager.GetString("Enum_FluxTypeItem_NoClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 2.
        /// </summary>
        public static string Enum_IPCClassItem_Class2 {
            get {
                return ResourceManager.GetString("Enum_IPCClassItem_Class2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 3.
        /// </summary>
        public static string Enum_IPCClassItem_Class3 {
            get {
                return ResourceManager.GetString("Enum_IPCClassItem_Class3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Enum_ItarItem_No {
            get {
                return ResourceManager.GetString("Enum_ItarItem_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Enum_ItarItem_Yes {
            get {
                return ResourceManager.GetString("Enum_ItarItem_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Enum_LeadFree_No {
            get {
                return ResourceManager.GetString("Enum_LeadFree_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Enum_LeadFree_Yes {
            get {
                return ResourceManager.GetString("Enum_LeadFree_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material 1.
        /// </summary>
        public static string Enum_MaterialItem_Material1 {
            get {
                return ResourceManager.GetString("Enum_MaterialItem_Material1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material 2.
        /// </summary>
        public static string Enum_MaterialItem_Material2 {
            get {
                return ResourceManager.GetString("Enum_MaterialItem_Material2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material 3.
        /// </summary>
        public static string Enum_MaterialItem_Material3 {
            get {
                return ResourceManager.GetString("Enum_MaterialItem_Material3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Notes.
        /// </summary>
        public static string Enum_StackupItem_SeeNotes {
            get {
                return ResourceManager.GetString("Enum_StackupItem_SeeNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Enum_StackupItem_Standard {
            get {
                return ResourceManager.GetString("Enum_StackupItem_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficalt surface.
        /// </summary>
        public static string Enum_SurfaceFinishItem_DifficaltSurface {
            get {
                return ResourceManager.GetString("Enum_SurfaceFinishItem_DifficaltSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy surface.
        /// </summary>
        public static string Enum_SurfaceFinishItem_EasySurface {
            get {
                return ResourceManager.GetString("Enum_SurfaceFinishItem_EasySurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One day surface.
        /// </summary>
        public static string Enum_SurfaceFinishItem_OneDaySurface {
            get {
                return ResourceManager.GetString("Enum_SurfaceFinishItem_OneDaySurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both sides.
        /// </summary>
        public static string Enum_TentingViasItem_BothSides {
            get {
                return ResourceManager.GetString("Enum_TentingViasItem_BothSides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom side.
        /// </summary>
        public static string Enum_TentingViasItem_BottomSide {
            get {
                return ResourceManager.GetString("Enum_TentingViasItem_BottomSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_TentingViasItem_None {
            get {
                return ResourceManager.GetString("Enum_TentingViasItem_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top side.
        /// </summary>
        public static string Enum_TentingViasItem_TopSide {
            get {
                return ResourceManager.GetString("Enum_TentingViasItem_TopSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabrication.
        /// </summary>
        public static string Fabrication {
            get {
                return ResourceManager.GetString("Fabrication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux Type.
        /// </summary>
        public static string FluxType {
            get {
                return ResourceManager.GetString("FluxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Board Preferences.
        /// </summary>
        public static string ImportantBoardPreferences {
            get {
                return ResourceManager.GetString("ImportantBoardPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPC Class.
        /// </summary>
        public static string IPCClass {
            get {
                return ResourceManager.GetString("IPCClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITAR.
        /// </summary>
        public static string ITAR {
            get {
                return ResourceManager.GetString("ITAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Free.
        /// </summary>
        public static string LeadFree {
            get {
                return ResourceManager.GetString("LeadFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCB Manufacturing.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a Current order.
        /// </summary>
        public static string MakeOrder {
            get {
                return ResourceManager.GetString("MakeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing.
        /// </summary>
        public static string Manufacturing {
            get {
                return ResourceManager.GetString("Manufacturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string OrderHeader {
            get {
                return ResourceManager.GetString("OrderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place an Order.
        /// </summary>
        public static string PlaceAnOrder {
            get {
                return ResourceManager.GetString("PlaceAnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string PreferencesHeader {
            get {
                return ResourceManager.GetString("PreferencesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences on this page supersede design notes.
        /// </summary>
        public static string PreferencesHint {
            get {
                return ResourceManager.GetString("PreferencesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Basics.
        /// </summary>
        public static string ProjectBasics {
            get {
                return ResourceManager.GetString("ProjectBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string QuoteHeader {
            get {
                return ResourceManager.GetString("QuoteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runnig total.
        /// </summary>
        public static string RunnigTotal {
            get {
                return ResourceManager.GetString("RunnigTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Continue.
        /// </summary>
        public static string SaveAndContinue {
            get {
                return ResourceManager.GetString("SaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdkscreen Color.
        /// </summary>
        public static string SdkscreenColor {
            get {
                return ResourceManager.GetString("SdkscreenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solder Mask Color.
        /// </summary>
        public static string SolderMaskColor {
            get {
                return ResourceManager.GetString("SolderMaskColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Board Preferences.
        /// </summary>
        public static string SpecialBoardPreferences {
            get {
                return ResourceManager.GetString("SpecialBoardPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stackup.
        /// </summary>
        public static string Stackup {
            get {
                return ResourceManager.GetString("Stackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        public static string StatusHeader {
            get {
                return ResourceManager.GetString("StatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe your design and receive real-time design feedback for manufacturing and component sourcing. If you update your design we will provide an update quote.
        /// </summary>
        public static string StatusPlaceholderText {
            get {
                return ResourceManager.GetString("StatusPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface Finish.
        /// </summary>
        public static string SurfaceFinish {
            get {
                return ResourceManager.GetString("SurfaceFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenting for Vias.
        /// </summary>
        public static string TentingVias {
            get {
                return ResourceManager.GetString("TentingVias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Impact.
        /// </summary>
        public static string TimeImpact {
            get {
                return ResourceManager.GetString("TimeImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Values.
        /// </summary>
        public static string ValidValues {
            get {
                return ResourceManager.GetString("ValidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be delivered in.
        /// </summary>
        public static string WillBeDeliv {
            get {
                return ResourceManager.GetString("WillBeDeliv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your.
        /// </summary>
        public static string Your {
            get {
                return ResourceManager.GetString("Your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no orders yet. 
        /// Your orders will appear here..
        /// </summary>
        public static string YourOrder {
            get {
                return ResourceManager.GetString("YourOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode.
        /// </summary>
        public static string Zipcode {
            get {
                return ResourceManager.GetString("Zipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required to estimate shipping time.
        /// </summary>
        public static string ZipcodeToolTip {
            get {
                return ResourceManager.GetString("ZipcodeToolTip", resourceCulture);
            }
        }
    }
}
